name: Go

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [ master, development ]

jobs:

  before_script:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Set up golint
        run: sudo apt install golint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: go build -v ./...

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: go test -v ./...

  code_quality:
    name: Code Qaulity
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        run: golint -set_exit_status ./...
