name: Go

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [ master, development ]

jobs:

  before_script:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: go build -v ./...

#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Test
#        run: go test -v ./...

  code_quality:
    name: Code Qaulity
    runs-on: ubuntu-latest
    container: golangci/golangci-lint:v1.31.0
    steps:
      - name: Lint
        run: |
          golangci-lint run
